#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <string.h>
#include <math.h>
#include "simprob_utils.h"
#include "probabilidad.h"
#include "huffman_tree.h"
#include "huffman.h"
#include "number_utils.h"
#include "coder.h"
#include "string_utils.h"
#include "string_analyzer.h"
#include "string_list.h"
#define BYTES_PER_CHAR 8
char* huffmanSimple(char *input);
char* huffmanComplex(char *input, char *fileName);
int checkInput(char *input);
int checkChar(char character);
int main(int argc, char *argv[])
{
	char *fileName = NULL;
	int c;
	while((c = getopt(argc, argv,"hf:")) != -1){
		switch(c)
		{
			case 'f':
				fileName = argv[2];
				break;
			case 'h':
			default:
				printf("Uso: encode -f fileToCompress\n");
				return -1;
		}
	}
	if(fileName == NULL){
		printf("Uso: encode -f fileToCompress\n");
	}
	FILE *file = fopen(fileName, "r");
	if(file == NULL){
		printf("Error abriendo fichero %s.\n", fileName);
		return -1;
	}

	char *input = NULL;
	size_t len = 0;
	getline(&input, &len, file);
	input[strlen(input) - 1] = '\0'; //Eliminar retorno de carro final
	fclose(file);
	if (!checkInput(input)){
		printf("Error en la entrada. Solo son validos los simbolos 'A', 'T', 'C' o 'G'.\n");
		return -1;
	}

	char *binSimple = huffmanSimple(input);
	char *binComplex = huffmanComplex(input, fileName);
	int sizeHuffmanSimple = strlen(binSimple);
	int sizeHuffmanComplex = strlen(binComplex);
	int sizeNoCompress = strlen(input) * BYTES_PER_CHAR;
	double rcSimple = (double)sizeNoCompress / (double)sizeHuffmanSimple;
	double rcComplex = (double)sizeNoCompress / (double)sizeHuffmanComplex;
	printf("Relacion de compresion para el algoritmo simple: %d/%d=%.3f\n",sizeNoCompress, sizeHuffmanSimple, rcSimple);
	printf("Relacion de compresion para el algoritmo complejo: %d/%d=%.3f\n",sizeNoCompress, sizeHuffmanComplex, rcComplex);

	free(binSimple);
	free(binComplex);
	free(input);
	return 0;
}

int checkInput(char *input)
{
int check = 0, i;
	if(input != NULL){
		for(i = 0; i < strlen(input); i++){
			check = checkChar(input[i]);
			if(check == 0){
				break;
			}
			check = 1;
		}
	}
	return check;
}

int checkChar(char character)
{
	return character == ADENINE || character == GUANINE || character == CYTOSINE || character == THYMINE;
}





	//"ACCTTCATACCTCACAACCTTACGACCT";
	//"CTCGAGGGGCCTAGACATTGCCCTCCAGAGAGAGCACCCAACACCCTCCAGGCTTGACCGGCCAGGGTGTCCCCTTCCTACCTTGGAGAGAGCAGCCCCAGGGCATCCTGCAGGGGGTGCTGGGACACCAGCTGGCCTTCAAGGTCTCTGCCTCCCTCCAGCCACCCCACTACACGCTGCTGGGATCCTGGATCTCAGCTCCCTGGCCGACAACACTGGCAAACTCCTACTCATCCACGAAGGCCCTCCTGGGCATGGTGGTCCTTCCCAGCCTGGCAGTCTGTTCCTCACACACCTTGTTAGTGCCCAGCCCCTGAGGTTGCAGCTGGGGGTGTCTCTGAAGGGCTGTGAGCCCCCAGGAAGCCCTGGGGAAGTGCCTGCCTTGCCTCCCCCCGGCCCTGCCAGCGCCTGGCTCTGCCCTCCTACCTGGGCTCCCCCCATCCAGCCTCCCTCCCTACACACTCCTCTCAAGGAGGCACCCATGTCCTCTCCAGCTGCCGGGCCTCAGAGCACTGTGGCGTCCTGGGGCAGCCACCGCATGTCCTGCTGTGGCATGGCTCAGGGTGGAAAGGGCGGAAGGGAGGGGTCCTGCAGATAGCTGGTGCCCACTACCAAACCCGCTCGGGGCAGGAGAGCCAAAGGCTGGGTGTGTGCAGAGCGGCCCCGAGAGGTTCCGAGGCTGAGGCCAGGGTGGGACATAGGGATGCGAGGGGCCGGGGCACAGGATACTCCAACCTGCCTGCCCCCATGGTCTCATCCTCCTGCTTCTGGGACCTCCTGATCCTGCCCCTGGTGCTAAGAGGCAGGTAAGGGGCTGCAGGCAGCAGGGCTCGGAGCCCATGCCCCCTCACCATGGGTCAGGCTGGACCTCCAGGTGCCTGTTCTGGGGAGCTGGGAGGGCCGGAGGGGTGTACCCCAGGGGCTCAGCCCAGATGACACTATGGGGGTGATGGTGTCATGGGACCTGGCCAGGAGAGGGGAGATGGGCTCCCAGAAGAGGAGTGGGGGCTGAGAGGGTGCCTGGGGGGCCAGGACGGAGCTGGGCCAGTGCACAGCTTCCCACACCTGCCCACCCCCAGAGTCCTGCCGCCACCCCCAGATCACACGGAAGATGAGGTCCGAGTGGCCTGCTGAGGACTTGCTGCTTGTCCCCAGGTCCCCAGGTCATGCCCTCCTTCTGCCACCCTGGGGAGCTGAGGGCCTCAGCTGGGGCTGCTGTCCTAAGGCAGGGTGGGAACTAGGCAGCCAGCAGGGAGGGGACCCCTCCCTCACTCCCACTCTCCCACCCCCACCACCTTGGCCCATCCATGGCGGCATCTTGGGCCATCCGGGACTGGGGACAGGGGTCCTGGGGACAGGGGTCCGGGGACAGGGTCCTGGGGACAGGGGTGTGGGGACAGGGGTCTGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTCTGGGGACAGGGGTGTGGGGACAGGGGTCCGGGGACAGGGGTGTGGGGACAGGGGTCTGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTCTGGGGACAGGGGTGTGGGGACAGGGGTCCTGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTCCTGGGGATAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTCCCGGGGACAGGGGTGTGGGGACAGGGGTGTGGGGACAGGGGTCCTGGGGACAGGGGTCTGAGGACAGGGGTGTGGGCACAGGGGTCCTGGGGACAGGGGTCCTGGGGACAGGGGTCCTGGGGACAGGGGTCTGGGGACAGCAGCGCAAAGAGCCCCGCCCTGCAGCCTCCAGCTCTCCTGGTCTAATGTGGAAAGTGGCCCAGGTGAGGGCTTTGCTCTCCTGGAGACATTTGCCCCCAGCTGTGAGCAGGGACAGGTCTGGCCACCGGGCCCCTGGTTAAGACTCTAATGACCCGCTGGTCCTGAGGAAGAGGTGCTGACGACCAAGGAGATCTTCCCACAGACCCAGCACCAGGGAAATGGTCCGGAAATTGCAGCCTCAGCCCCCAGCCATCTGCCGACCCCCCCACCCCGCCCTAATGGGCCAGGCGGCAGGGGTTGACAGGTAGGGGAGATGGGCTCTGAGACTATAAAGCCAGCGGGGGCCCAGCAGCCCTCAGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTCCAAGGGCCTTTGCGTCAGGTGGGCTCAGGGTTCCAGGGTGGCTGGACCCCAGGCCCCAGCTCTGCAGCAGGGAGGACGTGGCTGGGCTCGTGAAGCATGTGGGGGTGAGCCCAGGGGCCCCAAGGCAGGGCACCTGGCCTTCAGCCTGCCTCAGCCCTGCCTGTCTCCCAGATCACTGTCCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGGTGAGCCAACCGCCCATTGCTGCCCCTGGCCGCCCCCAGCCACCCCCTGCTCCTGGCGCTCCCACCCAGCATGGGCAGAAGGGGGCAGGAGGCTGCCACCCAGCAGGGGGTCAGGTGCACTTTTTTAAAAAGAAGTTCTCTTGGTCACGTCCTAAAAGTGACCAGCTCCCTGTGGCCCAGTCAGAATCTCAGCCTGAGGACGGTGTTGGCTTCGGCAGCCCCGAGATACATCAGAGGGTGGGCACGCTCCTCCCTCCACTCGCCCCTCAAACAAATGCCCCGCAGCCCATTTCTCCACCCTCATTTGATGACCGCAGATTCAAGTGTTTTGTTAAGTAAAGTCCTGGGTGACCTGGGGTCACAGGGTGCCCCACGCTGCCTGCCTCTGGGCGAACACCCCATCACGCCCGGAGGAGGGCGTGGCTGCCTGCCTGAGTGGGCCAGACCCCTGTCGCCAGCCTCACGGCAGCTCCATAGTCAGGAGATGGGGAAGATGCTGGGGACAGGCCCTGGGGAGAAGTACTGGGATCACCTGTTCAGGCTCCCACTGTGACGCTGCCCCGGGGCGGGGGAAGGAGGTGGGACATGTGGGCGTTGGGGCCTGTAGGTCCACACCCAGTGTGGGTGACCCTCCCTCTAACCTGGGTCCAGCCCGGCTGGAGATGGGTGGGAGTGCGACCTAGGGCTGGCGGGCAGGCGGGCACTGTGTCTCCCTGACTGTGTCCTCCTGTGTCCCTCTGCCTCGCCGCTGTTCCGGAACCTGCTCTGCGCGGCACGTCCTGGCAGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAGACGCAGCCTGCAGGCAGCCCCACACCCGCCGCCTCCTGCACCGAGAGAGATGGAATAAAGCCCTTGAACCAGCCCTGCTGTGCCGTCTGTGTGTCTTGGGGGCCCTGGGCCAAGCCCCACTTCCCGGCACTGTTGTGAGCCCCTCCCAGCTCTCTCCACGCTCTCTGGGTGCCCACAGGTGCCAACGCCGGCCAGGCCCAGCATGCAGTGGCTCTCCCCAAAGCGGCCATGCCTGTTGGCTGCCTGCTGCCCCCACCCTGTGGCTCAGGGTCCAGTATGGGAGCTTCGGGGGTCTCTGAGGGGCCAGGGATGGTGGGGCCACTGAGAAGTGACTTCTTGTTCAGTAGCTCTGGACTCTTGGAGTCCCCAGAGACCTTGTTCAGGAAAGGGAATGAGAACATTCCAGCAATTTTCCCCCCACCTAGCCCTCCCAGGTTCTATTTTTAGAGTTATTTCTGATGGAGTCCCTGTGGAGGGAGGAGGCTGGGCTGAGGGAGGGGGT";
	//"ATCCCCATCCCCATCCCCATCCCCATCCCCATCCCC";


char* huffmanSimple(char *input)
{
	char *alphabet[] = {"A", "T", "C", "G"};
	double *symbolFrequency = charFreq(input, "ATCG");
	HuffmanTable *table = huffman(symbolFrequency, alphabet, 4);
	printf("Tabla de Huffman para el algoritmo simple:\n");
	printHuffmanTable(table);
	char *bin = getBinaryString(input, table);
	char* original = getOriginalMessage(bin, table);
	if(strcmp(input, original) != 0){
		printf("Hay errores al comprimir y descomprimir la cadena usando Huffman simple\n");
	} 
	printf("%zu bits ocupados al comprimir usando algoritmo simple.\n\n", strlen(bin));
	freeHuffmanTable(table);
	free(original);
	free(symbolFrequency);
	return bin;
}

char* huffmanComplex(char *input, char *fileName)
{
	char *tableFileName = concat(fileName, "_table");
	char *binFileName = concat(fileName, "_bin");
	char *alphabet = "ATCG";
	StringValueList *symbols = groupSymbols(input, alphabet);
	HuffmanTable *table = huffman(symbols->value, symbols->string, symbols->length);
	exportHuffmanTableToFile(table, tableFileName);
	printf("Tabla de Huffman para el algoritmo complejo:\n");
	printHuffmanTable(table);
	char *bin = getBinaryString(input, table);
	FILE *file = fopen(binFileName, "w");
	if (file != NULL){
		fputs(bin, file);
		fclose(file);
	}
	char* original = getOriginalMessage(bin, table);
	if(strcmp(input, original) != 0){
		printf("Hay errores al comprimir y descomprimir la cadena\n");
	} 
	printf("%zu bits ocupados al comprimir usando algoritmo complejo.\n\n", strlen(bin));
	freeStringValueList(symbols);
	freeHuffmanTable(table);
	free(original);
	free(tableFileName);
	free(binFileName);
	return bin;
}
